// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace C__Cook_API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211106153806_createdb2")]
    partial class createdb2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("DeliveryOption", b =>
                {
                    b.Property<int>("DeliveryOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarehouseLocation")
                        .HasColumnType("TEXT");

                    b.HasKey("DeliveryOptionId");

                    b.ToTable("DeliveryOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
